# def bubble_sort(lista1, lista2):
#     elementos = len(lista1)-1
#     ordenado = False
#     while not ordenado:
#         ordenado = True
#         for i in range(elementos):
#             if lista1[i] > lista1[i+1]:
#                 lista1[i], lista1[i+1] = lista1[i+1],lista1[i]
#                 lista2[i], lista2[i+1] = lista2[i+1],lista2[i]
#                 ordenado = False 
#     return lista1, lista2




# string = 'OMQEMDUEQMEK'
# s3 = 'CAESARISEASY'
# s4 = 'BRUTE'
# p1 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
# p2 = ''
# out = ''
# for i in string:
#     if i == ' ': 
#         out+=i
#         continue
#     out += p1[p2.find(i)]
# print(out)
# out = ''

# f1 = 'YYICS JIZIB AGYYX RIEWV IXAFN JOOVQ QVHDL CRKLB SSLYX RIQYI IOXQT WXRIC RVVKP BHZXI YLYZP DLCDI IKGFJ UXRIP TFQGL CWVXR IEZRV NMYSF JDLCL RXOWJ NMINX FNJSP JGHVV ERJTT OOHRM VMBWN JTXKG JJJXY TSYKL OQZFT OSRFN JKBIY YSSHE LIKLO RFJGS VMRJC CYTCS VHDLC LRXOJ MWFYB JPNVR NWUMZ GRVMF UPOEB XKSDL CBZGU IBBZX MLMKK LOACX KECOC IUSBS RMPXR IPJZW XSPTR HKRQB VVOHR MVKEE PIZEX SDYYI QERJJ RYSLJ VZOVU NJLOW RTXSD LYYNE ILMBK LORYW VAOXM KZRNL CWZRA YGWVH DLCLZ VVXFF KASPJ GVIKW WWVTV MCIKL OQYSW SBAFJ EWRII SFACC MZRVO MLYYI MSSSK VISDY YIGML PZICW FJNMV PDNEH ISSFE HWEIJ PSEEJ QYIBW JFMIC TCWYE ZWLTK WKMBY YICGY WVGBS UKFVG IKJRR DSBJJ XBSWM VVYLR MRXSW BNWJO VCSKW KMBYY IQYYW UMKRM KKLOK YYVWX SMSVL KWCAV VNIQY ISIIB MVVLI DTIIC SGSRX EVYQC CDLMZ XLDWF JNSEP BRROO WJFMI CSDDF YKWQM VLKWM KKLOV CXKFE XRFBI MEPJW SBWFJ ZWGMA PVHKR BKZIB GCFEH WEWSF XKPJT NCYYR TUICX PTPLO VIJVT DSRMV AOWRB YIBIR MVWER QJKWK RBDFY MELSF XPEGQ KSPML IYIBX FJPXR ELPVH RMKFE HLEBJ YMWKM TUFII YSUXE VLJUX YAYWU XRIUJ JXGEJ PZRQS TJIJS IJIJS PWMKK KBEQX USDXC IYIBI YSUXR IPJNM DLBFZ WSIQF EHLYR YVVMY NXUSB SRMPW DMJQN SBIRM VTBIR YPWSP IIIIC WQMVL KHNZK SXMLY YIZEJ FTILY RSFAD SFJIW EVNWZ WOWFJ WSERB NKAKW LTCSX KCWXV OILGL XZYPJ NLSXC YYIBM ZGFRK VMZEH DSRTJ ROGIM RHKPQ TCSCX GYJKB ICSTS VSPFE HGEQF JARMR JRWNS PTKLI WBWVW CXFJV QOVYQ UGSXW BRWCS MSCIP XDFIF OLGSU ECXFJ PENZY STINX FJXVY YLISI MEKJI SEKFJ IEXHF NCPSI PKFVD LCWVA OVCSF JKVKX ESBLM ZJICM LYYMC GMZEX BCMKK LOACX KEXHR MVKBS SSUAK WSSKM VPCIZ RDLCF WXOVL TFRDL CXLRC LMSVL YXGSK LOMPK RGOWD TIXRI PJNIB ILTKV OIQYF SPJCW KLOQQ MRHOW MYYED FCKFV ORGLY XNSPT KLIEL IKSDS YSUXR IJNFR GIPJK MBIBF EHVEW IFAXY NTEXR IEWRW CELIW IVPYX CIOTU NKLDL CBFSN QYSRR NXFJJ GKVCH ISGOC JGMXK UFKGR'
# f2 = 'YYIIA CWVSL PGLVH DSAFD TYYRY YEDRG LYXER BJIEV EPLVX BICNE XRIDT IICXD TIXRI PJNIB ILTYS EWCXE IKVRM VXBIC RRHOE ETFHD LGHBG YZCWZ RQXMU ISDIA YKLOQ DWFQD LCIVA KRBYY IDMLB FSNQY STLYT NJUEQ VCFKT SPCTW AYSBB ZXRLG XRBOE LIUSB SRMPF EMJYR WZPCS UMNJG WVXRE RBRVW IBMVV KRBRR HOLCW WIOPJ JJWVS LJCCC LCFEH DSRTR XOXFJ CECXM KKLOM PGIIK HYSUR YAQMV HSHLT KOXSU BYEDX FJPAY YJIUS PSPGI IKODF JXSJW TLASW FXRMN XFJCM YRGBZ PVKMN EXYXF JWSBI QYRRN OGQCE NICWW SBCMZ PSEGY SISKW RNKFI XFJWM BIQNE GOCMZ IXKWR JJEBI QTGIM YJNRV DLYYP SETPJ WIBGM TBINJ MTUEX HRMVR ISSBZ PVLYA VEFIP DXSYH ZWVEU JYXKH YRRUC IKWCI FRDFC LXINX FJKMX AMTUQ KRGXY SEPBH VVDEG SCCGI CUZJI SSPZP VIBFG SYVBJ VVKRB YYIXQ WORAC AMZCH BYQYR KKMLG LXDLC QZSXA CSKEG EWNEX YXFJW SBIQY RRNJM ZEHRM QTNRC YNUVV KRBSF SXICA VVURC BNLKX GYNEC JMWYI NMBSK QORRN FRSXY SUXRI QHRVO GPTNJ YYLIR XBICK LPVSD SLXCE LIWMV PCIUS BSRMP WLEQP VXGMR MKLOQ QTKLK XQMVA YYJIE SDFCM LRQVW KFVKP MSXXS QCXYI DLMZX LDXFN JAKWT JICUM LIRRN XFTLK RXDZC SPXFJ JGKVC HISGF SYJLO PYZXL OHFJR VDMJD RXDLC FNOGE PINEI MLBYM MLRMV TYSPH IIKXS WVTSG IJUYZ XFJEY DWFNJ TKHBJ ULKRB XNIBI QTTPE QQDRR NXFJE YDWUJ IICSQ RRPVX FFKLO HPTGT OHYQD SCXYX DEXCY XYIZY RNEXR IZFJO OXZZK XRIQH RVOGP TNHSH LTKQS RBMFA VSLLZ XDSMP YMWXM KZPVX FJSEC OCYWS BMRJE ELPCI YMWXM PVIZE UFPJB SKYYI PMPJR WRIDJ RVOHY XGEBO KNXLD KCYZR DSFNJ WDVYB RRNFS WELSQ SUJSR IIJGX KKMTU HSWRF EGOEU FPJBS KYYIP PYRVW KRBTE PIGYR VROEP YFGYZ CWUSB SRMPA SXFII CVIYA VWGLC SJLOP YDUSG RRTJP OINYY ICIIJ GXRIP AVVIW LZXEX HUFIQ KRBXY ICPCU KWYYL ICCER RNCQY VLNEK GLCSZ XGEQI RCVME MKXRI ENIPL ERMVH RIPKR GOMLF CMDXJ JIMZT JNEKL VMTBE XHQTF RKJRJ IXRIW FCPCX YWKIN XMBRV NXFJV QOVYQ UGSXW YYMCA YXKSL IYSVZ ORRKL PNEWK FVDLC YIEFI JJIWD LCDYE NLYWU PIFCJ EAKPI NEKKR FTLVG LCSKL OCQFN FOJMW VXRIK FXVOE RIZXM LRMRX MVMXJ INXFJ ISKHY SUHSZ GIVHD LCKFV OWRFJ JKVYX KLOCA TLPNW CJFRO MRMVV CMBJZ XGEQF MIBCU NUINM RHYEX HUMVR DLCDT VOTRZ GXYXF JVHQI YSUPY SIJUM XXMNK XRIWH FYVHQ JVMDA YXRPC STJIC NICUR RNXFJ IIGIP JDEXC ZNXNK KEJUV YGIXR XDLCG FXDSK YYICM BJJAO VCXFW DICUK LKXLT EIYJR MVQMS SQUGV MKGUS GRYSU JYVYR FQORR NKWOI KJUXR ERYYI SVHTL VXIWR LWDIL INLKX QMRPV ACIFE COCIU SBSRM PHOWN FZVSR EQPMR ETJEX DLCKR MXXCX KMNIY XRMNX FJKMX AMTUQ KRYSU XRIJN FRCLM TBLSW QMRKQ CKFEI KRBQF SUIBY YSEKF YWYVF SYKLO WAFII MVMBJ ESHUJ TEXRM YWPIX FFKMC GCWKE SRLJZ XRIPH RRGIA QZQLH MBEMX XMYYM CKPJR XNMRH YXRIP JWSBI GKNIM ELSFX TYKUF ZOVGY NIWYQ YJXYT UMVVO ACFII SXFNE OSGMZ CHTYK UFZOV GYJES HRMVG YAYWU PIPGT EEPXC WDIKW SWZRQ XFJUM CXYST IMEPJ WYVPW NELSW KNEHD LCSNI KVCFC PBMEM KEXWU JIINX FJJGK VCHIS GJMWP SEGYS TEBVW ZJEVP MAVVY RWTLV LEAPF ROERF KMWIU JCPSP JYICS XQFZH DLCQZ SXAFT NMVPE TWMBW RNNMV PBJTP KVCIK LOWAF IIMVM BWSBM DDFYP SSSUX RERDF YMSSQ URYXH ZDTYZ CWKLO KSQWH YVMYY CGSSQ UFOOG QCINS PYYID MLBFS NQYSS ENPWI VRDIB TEXRI PTTOC FCQFA LYRNW MKQMS PSEVZ FTOSX UNCPX SRRRX DIPXF QEGFK FVDLC KRPVA MZCHX SRMLV DQCFK EVP'
# str1, str2, str3, str4, str5, str0 = '','','','','','' 
# f = (f1 + f2).replace(' ', '')
# key = ''
# for i in range(len(f)):
#     match i%6:
#         case 0: str0+=f[i]
#         case 1: str1+=f[i]
#         case 2: str2+=f[i]
#         case 3: str3+=f[i]
#         case 4: str4+=f[i]
#         case 5: str5+=f[i]
# print("\n\n")
# for j in [str0,str1,str2,str3,str4,str5]:
#     l1 = []
#     l2 = []
#     for i in p1: 
#         l1.append(j.count(i))
#         l2.append(i)

#     l1, l2 = bubble_sort(l1, l2)
#     for i in range(len(l1)):
#         print(l1[i], ': ', l2[i])
#     print("\n\n\n")
        
# k = 0
# key = 'SQDXEX'
# key = 'FREKEY'

# pssd = 'HCIKVRJOX'
# for i in pssd:
#     print(p1.index(key[k]), p1.index(i))
#     if p1.index(key[k]) + p1.index(i) -1> 25:
#         out += p1[p1.index(key[k])+ p1.index(i) -1-26]
#     else:
#         out += p1[p1.index(key[k])+ p1.index(i)-1]
#     k += 1
#     if k > 5:
#         k = 0
# print(out)
# out = ''

# print("\n\n")

# for i in f1.replace(' ', ''):
#     if p1.index(key[k]) + p1.index(i) +1> 25:
#         out += p1[p1.index(key[k])+ p1.index(i) +1 -26]
#     else:
#         out += p1[p1.index(key[k])+ p1.index(i) +1]
#     k += 1
#     if k > 5:
#         k = 0
# print(out)

# input = 'PNUKLYLWRQKGKBE'
# key = 'EICTDGYIYZKTHNS'
# base = ord('A')
# flag = ''
# for c_in, shift in zip(input, key):
#     flag += chr( (ord(c_in) - ord(shift) - 2*base)%26 + base)

# print(flag)

caesar = '1E 46 46 3B 20 41 46 39 03 20 50 46 4C 20 4A 46 \
43 4D 3C 3B 20 46 45 3C 20 44 46 49 3C 20 3A 3F \
38 43 43 3C 45 3E 3C 20 40 45 20 50 46 4C 49 20 \
41 46 4C 49 45 3C 50 05 20 2B 3F 40 4A 20 46 45 \
3C 20 4E 38 4A 20 3D 38 40 49 43 50 20 3C 38 4A \
50 20 4B 46 20 3A 49 38 3A 42 05 20 2E 38 4A 45 \
7E 4B 20 40 4B 16 20 08 09 0F 20 42 3C 50 4A 20 \
40 4A 20 38 20 48 4C 40 4B 3C 20 4A 44 38 43 43 \
20 42 3C 50 4A 47 38 3A 3C 03 20 4A 46 20 40 4B \
20 4A 3F 46 4C 43 3B 45 7E 4B 20 3F 38 4D 3C 20 \
4B 38 42 3C 45 20 50 46 4C 20 4B 46 46 20 43 46 \
45 3E 20 4B 46 20 3B 3C 3A 49 50 47 4B 20 4B 3F \
40 4A 20 44 3C 4A 4A 38 3E 3C 05 20 2E 3C 43 43 \
20 3B 46 45 3C 03 20 50 46 4C 49 20 4A 46 43 4C \
4B 40 46 45 20 40 4A 20 3D 44 40 39 43 43 3B 3D \
39 38 43 3C 05 '
asciis = caesar.split()
ascii_numbers = []
ascii_numbers_shifted = []
ascii_string_converted = ''
print(asciis)
var = 0
for k in asciis:
    ascii_numbers.append(int(k, 16))

for var in range(50):
    for j in ascii_numbers:
        if j + var < 255:
            ascii_numbers_shifted.append(j+var)
        else:
            ascii_numbers_shifted.append(j+var-256)
    for n in ascii_numbers_shifted:
        ascii_string_converted += chr(n)
    print(var)
    if ascii_string_converted.rfind('Well')> 0:
        
        print(ascii_string_converted+ '\n\n\n\n\n')


